version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=lrbsunday
    ports:
      - 13306:3306

  distsuperd:
    image: distsuperd
    build:
      context: .
      dockerfile: docker/distsuperd/Dockerfile
    ports:
      - 3378:3378
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/home/distsuper
#    entrypoint:
#      - ./docker/distsuperd/entrypoint.sh
    command: [ "distsuperd", "start", "-f" ]

  distsuperagent:
    image: distsuperagent
    build:
      context: .
      dockerfile: docker/distsuperagent/Dockerfile
    ports:
      - 3379:3379
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/home/distsuper
#    entrypoint:
#      - ./docker/distsuperagent/entrypoint.sh
    command: [ "distsuperagent", "start", "-f" ]
# 其他的两种写法也可
#    command: distsuperagent start
#    command:
#      - distsuperagent
#      - start