version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=lrbsunday
    ports:
      - 13306:3306
    networks:
      - distsuper

  distsuperd:
#    build:
#      context: .
#      dockerfile: docker/distsuperd/Dockerfile
    image: ccr.ccs.tencentyun.com/yijia/peiyin:distsuperd-v1
    ports:
      - 3378:3378
    networks:
      - distsuper
    depends_on:
      - database
    volumes:
      - ./distsuper/configure/distsuper-compose.ini:/etc/distsuper.ini
#      - .:/home/distsuper
    command: [ "distsuperd", "start", "-f" ]

  distsuperagent:
#    build:
#      context: .
#      dockerfile: docker/distsuperagent/Dockerfile
    image: ccr.ccs.tencentyun.com/yijia/peiyin:distsuperagent-v1
    ports:
      - 3379:3379
    networks:
      - distsuper
    depends_on:
      - database
    volumes:
      - ./distsuper/configure/distsuper-compose.ini:/etc/distsuper.ini
#      - .:/home/distsuper
    command: [ "distsuperagent", "start", "-f" ]
# 其他的两种写法也可
#    command: distsuperagent start
#    command:
#      - distsuperagent
#      - start


networks:
  distsuper:
